const teamMembers = [
  {
    firstName: "Daniel",
    surname: "Palacios",
    age: "21",
    city: "Madrid",
    hobby: "Crossfit",
    favoriteFood: "Croquetas",
    favoriteVideoGame: "Pokemon Perla",
    favoriteFilm: "Pretty Woman",
    favoriteBook: "Endgame",
    petName: "Sora",
  },
  {
    firstName: "Manuel",
    surname: "Benitez",
    age: "29",
    city: "Palma",
    hobby: "Ski",
    favoriteFood: "Empandas",
    favoriteVideoGame: "Catan",
    favoriteFilm: "",
    favoriteBook: "Shantaram",
    petName: "Shiva, Shaka, Mechi",
  },
];
